# Generated by Django 2.0.6 on 2018-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField()),
                ('is_hr', models.BooleanField()),
                ('is_interviewer', models.BooleanField()),
                ('is_manager', models.BooleanField()),
            ],
        ),
    ]
