# Generated by Django 2.0.6 on 2018-10-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_opening',
            name='closing_date',
        ),
    ]
