# Generated by Django 2.0.6 on 2018-10-17 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_remove_current_opening_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_opening',
            name='closing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
