# Generated by Django 2.0.6 on 2018-10-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20181017_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
