# Generated by Django 2.0.6 on 2018-10-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_recruitment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.Current_Opening')),
                ('tech_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.Technology')),
            ],
        ),
    ]
