# Generated by Django 2.0.6 on 2018-10-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_tech_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='reference_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.Recruitment_User'),
        ),
    ]
