# Generated by Django 2.0.6 on 2018-10-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_auto_20181018_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment_user',
            name='is_manager',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='recruitment_user',
            name='is_interviewer',
            field=models.NullBooleanField(),
        ),
    ]
