# Generated by Django 2.0.6 on 2018-10-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_auto_20181018_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment_user',
            name='is_admin',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='recruitment_user',
            name='is_hr',
            field=models.NullBooleanField(),
        ),
    ]
