# Generated by Django 2.0.6 on 2018-10-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_auto_20181018_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_opening',
            old_name='opening_date',
            new_name='opening_timestamp',
        ),
        migrations.AlterField(
            model_name='current_opening',
            name='desc',
            field=models.TextField(verbose_name='Opening Description'),
        ),
    ]
