# Generated by Django 2.0.6 on 2018-10-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_auto_20181018_0506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruitment_User',
            new_name='RecruitmentUser',
        ),
        migrations.RenameField(
            model_name='current_opening',
            old_name='closing_date',
            new_name='closing_timestamp',
        ),
    ]
