# Generated by Django 2.0.6 on 2018-10-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_auto_20181018_0524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current_Opening',
            new_name='CurrentOpening',
        ),
    ]
