# Generated by Django 2.0.6 on 2018-10-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_auto_20181018_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAppliedOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.Candidate')),
                ('current_opening_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.CurrentOpening')),
            ],
        ),
        migrations.RenameModel(
            old_name='Tech_Opening',
            new_name='TechnologyOpening',
        ),
    ]
