# Generated by Django 2.0.6 on 2018-10-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_auto_20181018_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentuser',
            name='is_admin',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruitmentuser',
            name='is_hr',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruitmentuser',
            name='is_interviewer',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruitmentuser',
            name='is_manager',
            field=models.NullBooleanField(default=False),
        ),
    ]
