# Generated by Django 2.0.6 on 2018-10-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_auto_20181023_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentuser',
            name='username',
            field=models.TextField(),
        ),
    ]
